"""configs/flights.csv -> the generalization-arm splits.

Excluded segments land in `drop`, a fold nothing reads, so val and train are cut
from the reduced pool only. Test comes from the base split unchanged.
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parent.parent


def write(path, name, base, drop):
    cfg = {"name": name, "seed": base["seed"], "test": base["test"],
           "val": base["val"], "drop": sorted(drop)}
    with open(path, "w") as f:
        f.write("# generated by scripts/make_splits.py -- do not hand-edit\n")
        yaml.safe_dump(cfg, f, sort_keys=False)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--flights", type=Path, default=ROOT / "configs" / "flights.csv")
    p.add_argument("--base", default="paper")
    p.add_argument("--cut", type=float, default=5.0)
    p.add_argument("--seed", type=int, default=0)
    a = p.parse_args()

    splits = ROOT / "configs" / "splits"
    base = yaml.safe_load((splits / f"{a.base}.yaml").read_text())
    d = pd.read_csv(a.flights).set_index("id")
    pool = d.drop(index=base["test"])

    slow = pool[pool.vmax <= a.cut]
    order = np.random.default_rng(a.seed).permutation(len(pool))
    cum = pool.n.values[order].cumsum()
    ctrl = pool.iloc[sorted(order[:np.searchsorted(cum, slow.n.sum()) + 1])]

    for name, sel in [("slow", slow), ("ctrl", ctrl)]:
        out = splits / f"gen_{name}.yaml"
        write(out, f"gen_{name}", base, set(pool.index) - set(sel.index))
        print(f"gen_{name}: {len(sel)}/{len(pool)} segments, {sel.n.sum()} rows, "
              f"vmax {sel.vmax.max():.1f} -> {out.name}")


if __name__ == "__main__":
    main()