function a1s = calc_a1s(Omega, v1, mu, alpha_s, K, att_rate)
%calc_a1s caculates lateral flapping angle
param=setParam();
p = att_rate(1);
q = att_rate(2);
a1s = -2*((-90*param.Ib*param.R^9*param.a*alpha_s*param.c*param.g^2*mu^4*param.rho + 360*param.Ib*param.R^8*param.a*alpha_s*param.c*param.e*param.g^2*mu^4*param.rho - 540*param.Ib*param.R^7*param.a*alpha_s*param.c*param.e^2*param.g^2*mu^4*param.rho + ... 
 360*param.Ib*param.R^6*param.a*alpha_s*param.c*param.e^3*param.g^2*mu^4*param.rho - 90*param.Ib*param.R^5*param.a*alpha_s*param.c*param.e^4*param.g^2*mu^4*param.rho - 90*param.Mb*param.R^9*param.a*alpha_s*param.c*param.e*param.g*mu^4*param.rho + ... 
 360*param.Mb*param.R^8*param.a*alpha_s*param.c*param.e^2*param.g*mu^4*param.rho - 540*param.Mb*param.R^7*param.a*alpha_s*param.c*param.e^3*param.g*mu^4*param.rho + ... 
 360*param.Mb*param.R^6*param.a*alpha_s*param.c*param.e^4*param.g*mu^4*param.rho - 90*param.Mb*param.R^5*param.a*alpha_s*param.c*param.e^5*param.g*mu^4*param.rho - 120*param.Ib*param.R^9*param.a*param.c*param.g^2*mu^3*param.rho*param.theta_0 - 90*param.Ib*param.R^9*param.a*param.c*param.g^2*mu^3*param.rho*param.theta_1 + ... 
 420*param.Ib*param.R^8*param.a*param.c*param.e*param.g^2*mu^3*param.rho*param.theta_0 + ... 
 420*param.Ib*param.R^8*param.a*param.c*param.e*param.g^2*mu^3*param.rho*param.theta_1 - 480*param.Ib*param.R^7*param.a*param.c*param.e^2*param.g^2*mu^3*param.rho*param.theta_0 - 750*param.Ib*param.R^7*param.a*param.c*param.e^2*param.g^2*mu^3*param.rho*param.theta_1 + ... 
 120*param.Ib*param.R^6*param.a*param.c*param.e^3*param.g^2*mu^3*param.rho*param.theta_0 + ... 
 600*param.Ib*param.R^6*param.a*param.c*param.e^3*param.g^2*mu^3*param.rho*param.theta_1 + ... 
 120*param.Ib*param.R^5*param.a*param.c*param.e^4*param.g^2*mu^3*param.rho*param.theta_0 - 150*param.Ib*param.R^5*param.a*param.c*param.e^4*param.g^2*mu^3*param.rho*param.theta_1 - 60*param.Ib*param.R^4*param.a*param.c*param.e^5*param.g^2*mu^3*param.rho*param.theta_0 - 60*param.Ib*param.R^4*param.a*param.c*param.e^5*param.g^2*mu^3*param.rho*param.theta_1 + ... 
 30*param.Ib*param.R^3*param.a*param.c*param.e^6*param.g^2*mu^3*param.rho*param.theta_1 - 120*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu^3*param.rho*param.theta_0 - 90*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu^3*param.rho*param.theta_1 + ... 
 420*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu^3*param.rho*param.theta_0 + ... 
 420*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu^3*param.rho*param.theta_1 - 480*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu^3*param.rho*param.theta_0 - 750*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu^3*param.rho*param.theta_1 + ... 
 120*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu^3*param.rho*param.theta_0 + ... 
 600*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu^3*param.rho*param.theta_1 + ... 
 120*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu^3*param.rho*param.theta_0 - 150*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu^3*param.rho*param.theta_1 - 60*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu^3*param.rho*param.theta_0 - 60*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu^3*param.rho*param.theta_1 + ... 
 30*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*mu^3*param.rho*param.theta_1 - 180*param.Ib*param.R^9*param.a*alpha_s*param.c*param.g^2*mu^2*param.rho + ... 
 840*param.Ib*param.R^8*param.a*alpha_s*param.c*param.e*param.g^2*mu^2*param.rho - 1500*param.Ib*param.R^7*param.a*alpha_s*param.c*param.e^2*param.g^2*mu^2*param.rho + ... 
 1200*param.Ib*param.R^6*param.a*alpha_s*param.c*param.e^3*param.g^2*mu^2*param.rho - 300*param.Ib*param.R^5*param.a*alpha_s*param.c*param.e^4*param.g^2*mu^2*param.rho - 120*param.Ib*param.R^4*param.a*alpha_s*param.c*param.e^5*param.g^2*mu^2*param.rho + ... 
 60*param.Ib*param.R^3*param.a*alpha_s*param.c*param.e^6*param.g^2*mu^2*param.rho - 180*param.Mb*param.R^9*param.a*alpha_s*param.c*param.e*param.g*mu^2*param.rho + ... 
 840*param.Mb*param.R^8*param.a*alpha_s*param.c*param.e^2*param.g*mu^2*param.rho - 1500*param.Mb*param.R^7*param.a*alpha_s*param.c*param.e^3*param.g*mu^2*param.rho + ... 
 1200*param.Mb*param.R^6*param.a*alpha_s*param.c*param.e^4*param.g*mu^2*param.rho - 300*param.Mb*param.R^5*param.a*alpha_s*param.c*param.e^5*param.g*mu^2*param.rho - 120*param.Mb*param.R^4*param.a*alpha_s*param.c*param.e^6*param.g*mu^2*param.rho + ... 
 60*param.Mb*param.R^3*param.a*alpha_s*param.c*param.e^7*param.g*mu^2*param.rho - 240*param.Ib*param.R^9*param.a*param.c*param.g^2*mu*param.rho*param.theta_0 - 180*param.Ib*param.R^9*param.a*param.c*param.g^2*mu*param.rho*param.theta_1 + ... 
 1000*param.Ib*param.R^8*param.a*param.c*param.e*param.g^2*mu*param.rho*param.theta_0 + ... 
 960*param.Ib*param.R^8*param.a*param.c*param.e*param.g^2*mu*param.rho*param.theta_1 - 1440*param.Ib*param.R^7*param.a*param.c*param.e^2*param.g^2*mu*param.rho*param.theta_0 - 2000*param.Ib*param.R^7*param.a*param.c*param.e^2*param.g^2*mu*param.rho*param.theta_1 + ... 
 600*param.Ib*param.R^6*param.a*param.c*param.e^3*param.g^2*mu*param.rho*param.theta_0 + ... 
 1920*param.Ib*param.R^6*param.a*param.c*param.e^3*param.g^2*mu*param.rho*param.theta_1 + ... 
 400*param.Ib*param.R^5*param.a*param.c*param.e^4*param.g^2*mu*param.rho*param.theta_0 - 600*param.Ib*param.R^5*param.a*param.c*param.e^4*param.g^2*mu*param.rho*param.theta_1 - 360*param.Ib*param.R^4*param.a*param.c*param.e^5*param.g^2*mu*param.rho*param.theta_0 - 320*param.Ib*param.R^4*param.a*param.c*param.e^5*param.g^2*mu*param.rho*param.theta_1 + ... 
 240*param.Ib*param.R^3*param.a*param.c*param.e^6*param.g^2*mu*param.rho*param.theta_1 + ... 
 40*param.Ib*param.R^2*param.a*param.c*param.e^7*param.g^2*mu*param.rho*param.theta_0 - 20*param.Ib*param.R*param.a*param.c*param.e^8*param.g^2*mu*param.rho*param.theta_1 - 240*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu*param.rho*param.theta_0 - 180*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu*param.rho*param.theta_1 + ... 
 1000*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu*param.rho*param.theta_0 + ... 
 960*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu*param.rho*param.theta_1 - 1440*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu*param.rho*param.theta_0 - 2000*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu*param.rho*param.theta_1 + ... 
 600*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu*param.rho*param.theta_0 + ... 
 1920*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu*param.rho*param.theta_1 + ... 
 400*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu*param.rho*param.theta_0 - 600*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu*param.rho*param.theta_1 - 360*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu*param.rho*param.theta_0 - 320*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu*param.rho*param.theta_1 + ... 
 240*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*mu*param.rho*param.theta_1 + ... 
 40*param.Mb*param.R^2*param.a*param.c*param.e^8*param.g*mu*param.rho*param.theta_0 - 20*param.Mb*param.R*param.a*param.c*param.e^9*param.g*mu*param.rho*param.theta_1)*Omega^5 + ... 
 (-45*param.Ib*param.R^9*param.a*param.c*param.g^2*mu^2*p*param.rho + 150*param.Ib*param.R^8*param.a*param.c*param.e*param.g^2*mu^2*p*param.rho + ... 
 90*param.Ib*param.R^8*param.a*param.c*param.g^2*mu^3*param.rho*v1 - 165*param.Ib*param.R^7*param.a*param.c*param.e^2*param.g^2*mu^2*p*param.rho - 360*param.Ib*param.R^7*param.a*param.c*param.e*param.g^2*mu^3*param.rho*v1 + ... 
 60*param.Ib*param.R^6*param.a*param.c*param.e^3*param.g^2*mu^2*p*param.rho + 540*param.Ib*param.R^6*param.a*param.c*param.e^2*param.g^2*mu^3*param.rho*v1 - 15*param.Ib*param.R^5*param.a*param.c*param.e^4*param.g^2*mu^2*p*param.rho - 360*param.Ib*param.R^5*param.a*param.c*param.e^3*param.g^2*mu^3*param.rho*v1 + ... 
 30*param.Ib*param.R^4*param.a*param.c*param.e^5*param.g^2*mu^2*p*param.rho + 90*param.Ib*param.R^4*param.a*param.c*param.e^4*param.g^2*mu^3*param.rho*v1 - 15*param.Ib*param.R^3*param.a*param.c*param.e^6*param.g^2*mu^2*p*param.rho - 45*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu^2*p*param.rho + ... 
 150*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu^2*p*param.rho + 90*param.Mb*param.R^8*param.a*param.c*param.e*param.g*mu^3*param.rho*v1 - 165*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu^2*p*param.rho - 360*param.Mb*param.R^7*param.a*param.c*param.e^2*param.g*mu^3*param.rho*v1 + ... 
 60*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu^2*p*param.rho + 540*param.Mb*param.R^6*param.a*param.c*param.e^3*param.g*mu^3*param.rho*v1 - 15*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu^2*p*param.rho - 360*param.Mb*param.R^5*param.a*param.c*param.e^4*param.g*mu^3*param.rho*v1 + ... 
 30*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu^2*p*param.rho + 90*param.Mb*param.R^4*param.a*param.c*param.e^5*param.g*mu^3*param.rho*v1 - 15*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*mu^2*p*param.rho - 90*param.Ib*param.R^9*param.a*param.c*param.g^2*p*param.rho + ... 
 360*param.Ib*param.R^8*param.a*param.c*param.e*param.g^2*p*param.rho + 180*param.Ib*param.R^8*param.a*param.c*param.g^2*mu*param.rho*v1 - 500*param.Ib*param.R^7*param.a*param.c*param.e^2*param.g^2*p*param.rho - 840*param.Ib*param.R^7*param.a*param.c*param.e*param.g^2*mu*param.rho*v1 + ... 
 240*param.Ib*param.R^6*param.a*param.c*param.e^3*param.g^2*p*param.rho + 1500*param.Ib*param.R^6*param.a*param.c*param.e^2*param.g^2*mu*param.rho*v1 - 1200*param.Ib*param.R^5*param.a*param.c*param.e^3*param.g^2*mu*param.rho*v1 + ... 
 40*param.Ib*param.R^4*param.a*param.c*param.e^5*param.g^2*p*param.rho + 300*param.Ib*param.R^4*param.a*param.c*param.e^4*param.g^2*mu*param.rho*v1 - 60*param.Ib*param.R^3*param.a*param.c*param.e^6*param.g^2*p*param.rho + ... 
 120*param.Ib*param.R^3*param.a*param.c*param.e^5*param.g^2*mu*param.rho*v1 - 60*param.Ib*param.R^2*param.a*param.c*param.e^6*param.g^2*mu*param.rho*v1 + ... 
 10*param.Ib*param.R*param.a*param.c*param.e^8*param.g^2*p*param.rho - 90*param.Mb*param.R^9*param.a*param.c*param.e*param.g*p*param.rho + ... 
 360*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*p*param.rho + 180*param.Mb*param.R^8*param.a*param.c*param.e*param.g*mu*param.rho*v1 - 500*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*p*param.rho - 840*param.Mb*param.R^7*param.a*param.c*param.e^2*param.g*mu*param.rho*v1 + ... 
 240*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*p*param.rho + 1500*param.Mb*param.R^6*param.a*param.c*param.e^3*param.g*mu*param.rho*v1 - 1200*param.Mb*param.R^5*param.a*param.c*param.e^4*param.g*mu*param.rho*v1 + ... 
 40*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*p*param.rho + 300*param.Mb*param.R^4*param.a*param.c*param.e^5*param.g*mu*param.rho*v1 - 60*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*p*param.rho + ... 
 120*param.Mb*param.R^3*param.a*param.c*param.e^6*param.g*mu*param.rho*v1 - 60*param.Mb*param.R^2*param.a*param.c*param.e^7*param.g*mu*param.rho*v1 + ... 
 10*param.Mb*param.R*param.a*param.c*param.e^9*param.g*p*param.rho)*Omega^4 + (-90*param.R^9*param.a*alpha_s*param.c*param.g^2*param.k_beta*mu^4*param.rho + ... 
 360*param.R^8*param.a*alpha_s*param.c*param.e*param.g^2*param.k_beta*mu^4*param.rho - 540*param.R^7*param.a*alpha_s*param.c*param.e^2*param.g^2*param.k_beta*mu^4*param.rho + ... 
 360*param.R^6*param.a*alpha_s*param.c*param.e^3*param.g^2*param.k_beta*mu^4*param.rho - 90*param.R^5*param.a*alpha_s*param.c*param.e^4*param.g^2*param.k_beta*mu^4*param.rho + ... 
 120*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu^3*param.rho*param.theta_0 + ... 
 80*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu^3*param.rho*param.theta_1 - 420*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu^3*param.rho*param.theta_0 - 360*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu^3*param.rho*param.theta_1 + ... 
 480*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu^3*param.rho*param.theta_0 + ... 
 600*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu^3*param.rho*param.theta_1 - 120*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu^3*param.rho*param.theta_0 - 400*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu^3*param.rho*param.theta_1 - 120*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu^3*param.rho*param.theta_0 + ... 
 60*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu^3*param.rho*param.theta_0 + ... 
 120*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu^3*param.rho*param.theta_1 - 40*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*mu^3*param.rho*param.theta_1 - 10*param.R^9*param.a*param.c*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 + ... 
 60*param.R^8*param.a*param.c*param.e*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 - 150*param.R^7*param.a*param.c*param.e^2*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 + ... 
 200*param.R^6*param.a*param.c*param.e^3*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 - 150*param.R^5*param.a*param.c*param.e^4*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 + ... 
 60*param.R^4*param.a*param.c*param.e^5*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 - 10*param.R^3*param.a*param.c*param.e^6*param.g^2*param.k_beta*mu^3*param.rho*param.theta_1 + ... 
 160*param.Mb*param.R^9*param.a*alpha_s*param.c*param.e*param.g*mu^2*param.rho - 480*param.Mb*param.R^8*param.a*alpha_s*param.c*param.e^2*param.g*mu^2*param.rho + ... 
 360*param.Mb*param.R^7*param.a*alpha_s*param.c*param.e^3*param.g*mu^2*param.rho + ... 
 160*param.Mb*param.R^6*param.a*alpha_s*param.c*param.e^4*param.g*mu^2*param.rho - 240*param.Mb*param.R^5*param.a*alpha_s*param.c*param.e^5*param.g*mu^2*param.rho + ... 
 40*param.Mb*param.R^3*param.a*alpha_s*param.c*param.e^7*param.g*mu^2*param.rho - 20*param.R^9*param.a*alpha_s*param.c*param.g^2*param.k_beta*mu^2*param.rho + ... 
 360*param.R^8*param.a*alpha_s*param.c*param.e*param.g^2*param.k_beta*mu^2*param.rho - 1140*param.R^7*param.a*alpha_s*param.c*param.e^2*param.g^2*param.k_beta*mu^2*param.rho + ... 
 1360*param.R^6*param.a*alpha_s*param.c*param.e^3*param.g^2*param.k_beta*mu^2*param.rho - 540*param.R^5*param.a*alpha_s*param.c*param.e^4*param.g^2*param.k_beta*mu^2*param.rho - 120*param.R^4*param.a*alpha_s*param.c*param.e^5*param.g^2*param.k_beta*mu^2*param.rho + ... 
 100*param.R^3*param.a*alpha_s*param.c*param.e^6*param.g^2*param.k_beta*mu^2*param.rho + ... 
 120*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu*param.rho*param.theta_0 + ... 
 96*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu*param.rho*param.theta_1 - 340*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu*param.rho*param.theta_0 - 384*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu*param.rho*param.theta_1 + ... 
 240*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu*param.rho*param.theta_0 + ... 
 520*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu*param.rho*param.theta_1 + ... 
 60*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu*param.rho*param.theta_0 - 192*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu*param.rho*param.theta_1 - 40*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu*param.rho*param.theta_0 - 120*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu*param.rho*param.theta_1 - 60*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu*param.rho*param.theta_0 + ... 
 64*param.Mb*param.R^4*param.a*param.c*param.e^6*param.g*mu*param.rho*param.theta_1 + ... 
 24*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*mu*param.rho*param.theta_1 + ... 
 20*param.Mb*param.R^2*param.a*param.c*param.e^8*param.g*mu*param.rho*param.theta_0 - 8*param.Mb*param.R*param.a*param.c*param.e^9*param.g*mu*param.rho*param.theta_1 - 120*param.R^9*param.a*param.c*param.g^2*param.k_beta*mu*param.rho*param.theta_0 - 84*param.R^9*param.a*param.c*param.g^2*param.k_beta*mu*param.rho*param.theta_1 + ... 
 660*param.R^8*param.a*param.c*param.e*param.g^2*param.k_beta*mu*param.rho*param.theta_0 + ... 
 576*param.R^8*param.a*param.c*param.e*param.g^2*param.k_beta*mu*param.rho*param.theta_1 - 1200*param.R^7*param.a*param.c*param.e^2*param.g^2*param.k_beta*mu*param.rho*param.theta_0 - 1480*param.R^7*param.a*param.c*param.e^2*param.g^2*param.k_beta*mu*param.rho*param.theta_1 + ... 
 660*param.R^6*param.a*param.c*param.e^3*param.g^2*param.k_beta*mu*param.rho*param.theta_0 + ... 
 1728*param.R^6*param.a*param.c*param.e^3*param.g^2*param.k_beta*mu*param.rho*param.theta_1 + ... 
 360*param.R^5*param.a*param.c*param.e^4*param.g^2*param.k_beta*mu*param.rho*param.theta_0 - 720*param.R^5*param.a*param.c*param.e^4*param.g^2*param.k_beta*mu*param.rho*param.theta_1 - 420*param.R^4*param.a*param.c*param.e^5*param.g^2*param.k_beta*mu*param.rho*param.theta_0 - 256*param.R^4*param.a*param.c*param.e^5*param.g^2*param.k_beta*mu*param.rho*param.theta_1 + ... 
 264*param.R^3*param.a*param.c*param.e^6*param.g^2*param.k_beta*mu*param.rho*param.theta_1 + ... 
 60*param.R^2*param.a*param.c*param.e^7*param.g^2*param.k_beta*mu*param.rho*param.theta_0 - 28*param.R*param.a*param.c*param.e^8*param.g^2*param.k_beta*mu*param.rho*param.theta_1)*Omega^3 + ... 
 (80*param.Mb*param.R^9*param.a*param.c*param.e*param.g*mu^2*p*param.rho - 240*param.Mb*param.R^8*param.a*param.c*param.e^2*param.g*mu^2*p*param.rho + ... 
 180*param.Mb*param.R^7*param.a*param.c*param.e^3*param.g*mu^2*p*param.rho + 80*param.Mb*param.R^6*param.a*param.c*param.e^4*param.g*mu^2*p*param.rho - 120*param.Mb*param.R^5*param.a*param.c*param.e^5*param.g*mu^2*p*param.rho + ... 
 20*param.Mb*param.R^3*param.a*param.c*param.e^7*param.g*mu^2*p*param.rho + 35*param.R^9*param.a*param.c*param.g^2*param.k_beta*mu^2*p*param.rho - 90*param.R^8*param.a*param.c*param.e*param.g^2*param.k_beta*mu^2*p*param.rho + ... 
 90*param.R^8*param.a*param.c*param.g^2*param.k_beta*mu^3*param.rho*v1 + 15*param.R^7*param.a*param.c*param.e^2*param.g^2*param.k_beta*mu^2*p*param.rho - 360*param.R^7*param.a*param.c*param.e*param.g^2*param.k_beta*mu^3*param.rho*v1 + ... 
 140*param.R^6*param.a*param.c*param.e^3*param.g^2*param.k_beta*mu^2*p*param.rho + ... 
 540*param.R^6*param.a*param.c*param.e^2*param.g^2*param.k_beta*mu^3*param.rho*v1 - 135*param.R^5*param.a*param.c*param.e^4*param.g^2*param.k_beta*mu^2*p*param.rho - 360*param.R^5*param.a*param.c*param.e^3*param.g^2*param.k_beta*mu^3*param.rho*v1 + ... 
 30*param.R^4*param.a*param.c*param.e^5*param.g^2*param.k_beta*mu^2*p*param.rho + ... 
 90*param.R^4*param.a*param.c*param.e^4*param.g^2*param.k_beta*mu^3*param.rho*v1 + ... 
 5*param.R^3*param.a*param.c*param.e^6*param.g^2*param.k_beta*mu^2*p*param.rho - 160*param.Mb*param.R^8*param.a*param.c*param.e*param.g*mu*param.rho*v1 + ... 
 480*param.Mb*param.R^7*param.a*param.c*param.e^2*param.g*mu*param.rho*v1 - 360*param.Mb*param.R^6*param.a*param.c*param.e^3*param.g*mu*param.rho*v1 - 160*param.Mb*param.R^5*param.a*param.c*param.e^4*param.g*mu*param.rho*v1 + ... 
 240*param.Mb*param.R^4*param.a*param.c*param.e^5*param.g*mu*param.rho*v1 - 40*param.Mb*param.R^2*param.a*param.c*param.e^7*param.g*mu*param.rho*v1 - 90*param.R^9*param.a*param.c*param.g^2*param.k_beta*p*param.rho + ... 
 360*param.R^8*param.a*param.c*param.e*param.g^2*param.k_beta*p*param.rho + 20*param.R^8*param.a*param.c*param.g^2*param.k_beta*mu*param.rho*v1 - 500*param.R^7*param.a*param.c*param.e^2*param.g^2*param.k_beta*p*param.rho - 360*param.R^7*param.a*param.c*param.e*param.g^2*param.k_beta*mu*param.rho*v1 + ... 
 240*param.R^6*param.a*param.c*param.e^3*param.g^2*param.k_beta*p*param.rho + 1140*param.R^6*param.a*param.c*param.e^2*param.g^2*param.k_beta*mu*param.rho*v1 - 1360*param.R^5*param.a*param.c*param.e^3*param.g^2*param.k_beta*mu*param.rho*v1 + ... 
 40*param.R^4*param.a*param.c*param.e^5*param.g^2*param.k_beta*p*param.rho + 540*param.R^4*param.a*param.c*param.e^4*param.g^2*param.k_beta*mu*param.rho*v1 - 60*param.R^3*param.a*param.c*param.e^6*param.g^2*param.k_beta*p*param.rho + ... 
 120*param.R^3*param.a*param.c*param.e^5*param.g^2*param.k_beta*mu*param.rho*v1 - 100*param.R^2*param.a*param.c*param.e^6*param.g^2*param.k_beta*mu*param.rho*v1 + ... 
 10*param.R*param.a*param.c*param.e^8*param.g^2*param.k_beta*p*param.rho + 720*param.Ib*K*param.Mb*param.R^4*param.e*param.g*v1 - 1920*param.Ib*K*param.Mb*param.R^3*param.e^2*param.g*v1 + ... 
 1440*param.Ib*K*param.Mb*param.R^2*param.e^3*param.g*v1 - 240*param.Ib*K*param.Mb*param.e^5*param.g*v1 + ... 
 720*param.Ib*K*param.R^4*param.g^2*param.k_beta*v1 - 1920*param.Ib*K*param.R^3*param.e*param.g^2*param.k_beta*v1 + ... 
 1440*param.Ib*K*param.R^2*param.e^2*param.g^2*param.k_beta*v1 - 240*param.Ib*K*param.e^4*param.g^2*param.k_beta*v1 - 720*param.Ib*param.Mb*param.R^5*param.e*param.g*q + ... 
 960*param.Ib*param.Mb*param.R^4*param.e^2*param.g*q - 240*param.Ib*param.Mb*param.R*param.e^5*param.g*q - 720*param.Ib*param.R^5*param.g^2*param.k_beta*q + ... 
 960*param.Ib*param.R^4*param.e*param.g^2*param.k_beta*q - 240*param.Ib*param.R*param.e^4*param.g^2*param.k_beta*q + ... 
 720*K*param.Mb^2*param.R^4*param.e^2*v1 - 1920*K*param.Mb^2*param.R^3*param.e^3*v1 + ... 
 1440*K*param.Mb^2*param.R^2*param.e^4*v1 - 240*K*param.Mb^2*param.e^6*v1 + 720*K*param.Mb*param.R^4*param.e*param.g*param.k_beta*v1 - 1920*K*param.Mb*param.R^3*param.e^2*param.g*param.k_beta*v1 + ... 
 1440*K*param.Mb*param.R^2*param.e^3*param.g*param.k_beta*v1 - 240*K*param.Mb*param.e^5*param.g*param.k_beta*v1 - 720*param.Mb^2*param.R^5*param.e^2*q + ... 
 960*param.Mb^2*param.R^4*param.e^3*q - 240*param.Mb^2*param.R*param.e^6*q - 720*param.Mb*param.R^5*param.e*param.g*param.k_beta*q + ... 
 960*param.Mb*param.R^4*param.e^2*param.g*param.k_beta*q - 240*param.Mb*param.R*param.e^5*param.g*param.k_beta*q)*Omega^2 + ... 
 (-960*param.Mb^2*param.R^5*param.e*param.g*mu + 1440*param.Mb^2*param.R^4*param.e^2*param.g*mu - 480*param.Mb^2*param.R^2*param.e^4*param.g*mu - 960*param.Mb*param.R^5*param.g^2*param.k_beta*mu + ... 
 1440*param.Mb*param.R^4*param.e*param.g^2*param.k_beta*mu - 480*param.Mb*param.R^2*param.e^3*param.g^2*param.k_beta*mu)*Omega + ... 
 720*K*param.Mb*param.R^4*param.e*param.g*param.k_beta*v1 - 1920*K*param.Mb*param.R^3*param.e^2*param.g*param.k_beta*v1 + ... 
 1440*K*param.Mb*param.R^2*param.e^3*param.g*param.k_beta*v1 - 240*K*param.Mb*param.e^5*param.g*param.k_beta*v1 + ... 
 720*K*param.R^4*param.g^2*param.k_beta^2*v1 - 1920*K*param.R^3*param.e*param.g^2*param.k_beta^2*v1 + ... 
 1440*K*param.R^2*param.e^2*param.g^2*param.k_beta^2*v1 - 240*K*param.e^4*param.g^2*param.k_beta^2*v1 - 720*param.Mb*param.R^5*param.e*param.g*param.k_beta*q + ... 
 960*param.Mb*param.R^4*param.e^2*param.g*param.k_beta*q - 240*param.Mb*param.R*param.e^5*param.g*param.k_beta*q - 720*param.R^5*param.g^2*param.k_beta^2*q + ... 
 960*param.R^4*param.e*param.g^2*param.k_beta^2*q - 240*param.R*param.e^4*param.g^2*param.k_beta^2*q)*Omega*param.a*param.c*param.g*param.rho/(5*param.R*((-9*param.Ib*param.R^8*param.a^2*param.c^2*param.g^3*mu^4*param.rho^2 + ... 
 36*param.Ib*param.R^7*param.a^2*param.c^2*param.e*param.g^3*mu^4*param.rho^2 - 54*param.Ib*param.R^6*param.a^2*param.c^2*param.e^2*param.g^3*mu^4*param.rho^2 + ... 
 36*param.Ib*param.R^5*param.a^2*param.c^2*param.e^3*param.g^3*mu^4*param.rho^2 - 9*param.Ib*param.R^4*param.a^2*param.c^2*param.e^4*param.g^3*mu^4*param.rho^2 - 9*param.Mb*param.R^8*param.a^2*param.c^2*param.e*param.g^2*mu^4*param.rho^2 + ... 
 36*param.Mb*param.R^7*param.a^2*param.c^2*param.e^2*param.g^2*mu^4*param.rho^2 - 54*param.Mb*param.R^6*param.a^2*param.c^2*param.e^3*param.g^2*mu^4*param.rho^2 + ... 
 36*param.Mb*param.R^5*param.a^2*param.c^2*param.e^4*param.g^2*mu^4*param.rho^2 - 9*param.Mb*param.R^4*param.a^2*param.c^2*param.e^5*param.g^2*mu^4*param.rho^2 + ... 
 36*param.Ib*param.R^8*param.a^2*param.c^2*param.g^3*param.rho^2 - 192*param.Ib*param.R^7*param.a^2*param.c^2*param.e*param.g^3*param.rho^2 + ... 
 400*param.Ib*param.R^6*param.a^2*param.c^2*param.e^2*param.g^3*param.rho^2 - 384*param.Ib*param.R^5*param.a^2*param.c^2*param.e^3*param.g^3*param.rho^2 + ... 
 120*param.Ib*param.R^4*param.a^2*param.c^2*param.e^4*param.g^3*param.rho^2 + 64*param.Ib*param.R^3*param.a^2*param.c^2*param.e^5*param.g^3*param.rho^2 - 48*param.Ib*param.R^2*param.a^2*param.c^2*param.e^6*param.g^3*param.rho^2 + ... 
 4*param.Ib*param.a^2*param.c^2*param.e^8*param.g^3*param.rho^2 + 36*param.Mb*param.R^8*param.a^2*param.c^2*param.e*param.g^2*param.rho^2 - 192*param.Mb*param.R^7*param.a^2*param.c^2*param.e^2*param.g^2*param.rho^2 + ... 
 400*param.Mb*param.R^6*param.a^2*param.c^2*param.e^3*param.g^2*param.rho^2 - 384*param.Mb*param.R^5*param.a^2*param.c^2*param.e^4*param.g^2*param.rho^2 + ... 
 120*param.Mb*param.R^4*param.a^2*param.c^2*param.e^5*param.g^2*param.rho^2 + 64*param.Mb*param.R^3*param.a^2*param.c^2*param.e^6*param.g^2*param.rho^2 - 48*param.Mb*param.R^2*param.a^2*param.c^2*param.e^7*param.g^2*param.rho^2 + ... 
 4*param.Mb*param.a^2*param.c^2*param.e^9*param.g^2*param.rho^2)*Omega^6 + (-9*param.R^8*param.a^2*param.c^2*param.g^3*param.k_beta*mu^4*param.rho^2 + ... 
 36*param.R^7*param.a^2*param.c^2*param.e*param.g^3*param.k_beta*mu^4*param.rho^2 - 54*param.R^6*param.a^2*param.c^2*param.e^2*param.g^3*param.k_beta*mu^4*param.rho^2 + ... 
 36*param.R^5*param.a^2*param.c^2*param.e^3*param.g^3*param.k_beta*mu^4*param.rho^2 - 9*param.R^4*param.a^2*param.c^2*param.e^4*param.g^3*param.k_beta*mu^4*param.rho^2 + ... 
 48*param.Mb*param.R^7*param.a^2*param.c^2*param.e^2*param.g^2*mu^2*param.rho^2 - 168*param.Mb*param.R^6*param.a^2*param.c^2*param.e^3*param.g^2*mu^2*param.rho^2 + ... 
 192*param.Mb*param.R^5*param.a^2*param.c^2*param.e^4*param.g^2*mu^2*param.rho^2 - 48*param.Mb*param.R^4*param.a^2*param.c^2*param.e^5*param.g^2*mu^2*param.rho^2 - 48*param.Mb*param.R^3*param.a^2*param.c^2*param.e^6*param.g^2*mu^2*param.rho^2 + ... 
 24*param.Mb*param.R^2*param.a^2*param.c^2*param.e^7*param.g^2*mu^2*param.rho^2 + ... 
 48*param.R^7*param.a^2*param.c^2*param.e*param.g^3*param.k_beta*mu^2*param.rho^2 - 168*param.R^6*param.a^2*param.c^2*param.e^2*param.g^3*param.k_beta*mu^2*param.rho^2 + ... 
 192*param.R^5*param.a^2*param.c^2*param.e^3*param.g^3*param.k_beta*mu^2*param.rho^2 - 48*param.R^4*param.a^2*param.c^2*param.e^4*param.g^3*param.k_beta*mu^2*param.rho^2 - 48*param.R^3*param.a^2*param.c^2*param.e^5*param.g^3*param.k_beta*mu^2*param.rho^2 + ... 
 24*param.R^2*param.a^2*param.c^2*param.e^6*param.g^3*param.k_beta*mu^2*param.rho^2 + ... 
 36*param.R^8*param.a^2*param.c^2*param.g^3*param.k_beta*param.rho^2 - 192*param.R^7*param.a^2*param.c^2*param.e*param.g^3*param.k_beta*param.rho^2 + ... 
 400*param.R^6*param.a^2*param.c^2*param.e^2*param.g^3*param.k_beta*param.rho^2 - 384*param.R^5*param.a^2*param.c^2*param.e^3*param.g^3*param.k_beta*param.rho^2 + ... 
 120*param.R^4*param.a^2*param.c^2*param.e^4*param.g^3*param.k_beta*param.rho^2 + ... 
 64*param.R^3*param.a^2*param.c^2*param.e^5*param.g^3*param.k_beta*param.rho^2 - 48*param.R^2*param.a^2*param.c^2*param.e^6*param.g^3*param.k_beta*param.rho^2 + ... 
 4*param.a^2*param.c^2*param.e^8*param.g^3*param.k_beta*param.rho^2)*Omega^4 + (2304*param.Ib*param.Mb^2*param.e^2*param.g + ... 
 4608*param.Ib*param.Mb*param.e*param.g^2*param.k_beta + 2304*param.Ib*param.g^3*param.k_beta^2 + ... 
 2304*param.Mb^3*param.e^3 + 4608*param.Mb^2*param.e^2*param.g*param.k_beta + 2304*param.Mb*param.e*param.g^2*param.k_beta^2)*Omega^2 + ... 
 2304*param.Mb^2*param.e^2*param.g*param.k_beta + 4608*param.Mb*param.e*param.g^2*param.k_beta^2 + ... 
 2304*param.g^3*param.k_beta^3));

end
